version: '3'

services:
  app:
    build:
      context: node
    container_name: app
    image: abauruel/node_codeeducation
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: bash -c "node index.js"
    networks:
      - mynetwork
    tty: true
    depends_on:
      - db
  
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - mynetwork
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  nginx:
    build:
      context: nginx
    container_name: nginx
    image: abauruel/nginx_codeeducation
    networks:
      - mynetwork
    ports:
      - "8080:80"
    depends_on:
      - app

networks:
  mynetwork:
    driver: bridge

